apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuyuu-router-hub
  namespace: fuyuu-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuyuu-router-hub
  template:
    metadata:
      labels:
        app: fuyuu-router-hub
    spec:
      containers:
      - name: fuyuu-router-hub
        image: ohkinozomu/fuyuu-router:0.0.2
        volumeMounts:
        - name: fuyuu-router-hub-config
          mountPath: /app/config
        command: ["/bin/sh", "-c"]
        args:
        - |
          /app/fuyuu-router hub -c /app/config/config.toml -b mosquitto.mosquitto:1883
      volumes:
      - name: fuyuu-router-hub-config
        configMap:
          name: fuyuu-router-hub-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fuyuu-router-hub-config
  namespace: fuyuu-router
data:
  config.toml: |
    [profiling]
    registry = "pyroscope"
    server_address = "http://pyroscope.pyroscope:4040"