apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-tester
  namespace: fuyuu-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-tester
  template:
    metadata:
      labels:
        app: curl-tester
    spec:
      containers:
      - name: curl-tester
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - sleep 3600