apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuyuu-router-agent-2
  namespace: fuyuu-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuyuu-router-agent-2
  template:
    metadata:
      labels:
        app: fuyuu-router-agent-2
    spec:
      containers:
      - name: fuyuu-router-agent-2
        image: fuyuu-router:dev
        command: ["/bin/sh", "-c"]
        args:
        - |
          /app/fuyuu-router agent --id agent02 -b nanomq.nanomq:1883 --proxy-host 127.0.0.1:8000 --loglevel debug
      - name: appserver
        image: golang:1.21.3
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo 'package main; import ("net/http"; "fmt"); func main() { http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintf(w, "Hello from agent02!") }); http.ListenAndServe(":8000", nil) }' > server.go && go run server.go
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5